### ISSUE TITLE
Timelapse

### ISSUE THREAD

**Issue by programical** [programical/gitland#43]
Since every turn is a commit, it should be possible to generate a timelapse of the game. Anyone interested?

**Comment by wcraigjones** [comment]
I'm commenting to remind myself to look at this tomorrow. I might be able to do it if it isnt done by then. Github actions sounds like a candidate.

**Comment by MrFastwind** [comment]
Like one created with [gource](https://gource.io/)? or something more text-like?

**Comment by programical** [comment]
> Like one created with [gource](https://gource.io/)? or something more text-like?

Something like [this](https://www.youtube.com/watch?v=XnRCZK3KjUY).

**Comment by MrFastwind** [comment]
> > Like one created with [gource](https://gource.io/)? or something more text-like?
> 
> Something like [this](https://www.youtube.com/watch?v=XnRCZK3KjUY).

the old /r/place,
it would be easier with an image, so probably is better to fetch every commit of the map and than render every change as a image and than crop it together.

**Comment by wmww** [comment]
[My bot](https://github.com/wmww/gitland-bot/) is built in Rust and open source except for the logic. It uses libgit to look up the game state. Right now it just looks up the most recent commit (so just the current state), but I plan to make it be aware of the full history. I'm also planning to make a visualizer, that could render such a time lapse.

**Comment by Kawzeg** [comment]
I created a quick [script](https://gist.github.com/Kawzeg/d6b6d9c5f0d1113ea744e724a24741f4) that collects all versions of the map file in a timelapse folder using gitpython.

**Comment by Drakor** [comment]
Here is a quick animation of the last 500 hundred or so turns, just in case anyone was curious how it actually looks: https://imgur.com/a/kbW2XTR

**Comment by programical** [comment]
> Here is a quick animation of the last 500 hundred or so turns, just in case anyone was curious about how it actually looks: https://imgur.com/a/kbW2XTR

Very nice! I can even tell which bot is mine by the way it behaves. I think it would be good to make the player characters full red/green/blue (FF0000, 00FF00, 0000FF). It's kind of hard to tell who's in which team.

**Comment by Kawzeg** [comment]
And here's one including all turns: https://imgur.com/Tv9YTA8

I updated the gist at https://gist.github.com/Kawzeg/d6b6d9c5f0d1113ea744e724a24741f4 with the changes if anyone wants to try at home. It takes forever, but that's what you get when you go from string -> markdown -> html -> pdf -> png -> mp4.

**Comment by MrFastwind** [comment]
> And here's one including all turns: https://imgur.com/Tv9YTA8
> 
> I updated the gist at https://gist.github.com/Kawzeg/d6b6d9c5f0d1113ea744e724a24741f4 with the changes if anyone wants to try at home. It takes forever, but that's what you get when you go from string -> markdown -> html -> pdf -> png -> mp4.

why are you doing this? its not better take the sting and make an image, and than make the mp4?

**Comment by Kawzeg** [comment]
Sure, but I didn't have the time to do it that way, so I did it this way. To be honest, I had hoped there was a tool for a direct markdown -> png conversion, but this is all I could come up with during my lunch break.

**Comment by Drakor** [comment]
Still, the result is quite neat.
I also finally managed to also render all turns from the very start, the result can be seen here: https://www.youtube.com/watch?v=PDK0Y_tiWf8

I tried to play around with the colors some more, but the default from the github here is probably the best. I'm using [this](https://gist.github.com/Drakor/af7b62e35e4a4417003c9b313eb8c290) to stitch the video together, but unfortunately, I don't know much about ffmpeg.

**Comment by programical** [comment]
@Drakor This is the best one so far. I like the added player & turn counter. Colors look good, too.

**Comment by Richienb** [comment]
I think the next step here is to show the player names to add some context to the moving boxes.

**Comment by MrFastwind** [comment]
> I think the next step here is to show the player names to add some context to the moving boxes.

the problem with that, is that you need the coordinate of every client (every directory in players x, y, team)
and make different colors for the representation on the board

**Comment by Richienb** [comment]
The player directory is updated alongside the log so it is possible in theory.

**Comment by MrFastwind** [comment]
> The player directory is updated alongside the log so it is possible in theory.

yes, it's only the fact that you need more data and the fact that map and users have a duplicated data (player position in present in the map without the reference to the player it self)

**Comment by Drakor** [comment]
It is indeed very possible, I've just uploaded a version which includes player names, as well as a rudimentary score calculation. I don't know why, but I completely forgot to also include the ratio between the colors, I guess thats something for the future.

Here are turns 1401 to 2907:
https://www.youtube.com/watch?v=KaEpvIWWk0w

I think the video might be a bit fast, especially if you want to read the player names. Once I manage to clean the code up a little, I will also post the code for it somewhere.

**Comment by Richienb** [comment]
@Drakor For now, can you dump the logic in a gist?

**Comment by programical** [comment]
In case you missed it: [The Fire Nation attacks.](https://www.youtube.com/watch?v=p9vKwSBBljI)

**Comment by Rialgar** [comment]
So how do we count turns? I just took 4a9cd04a52a2d92feab9f7757386c5e5dc4124ea as turn 1 and every commit that touches the map after that is a turn. I did not filter by commit message. Are you all doing the same thing?

BTW I am working on a thing that can show the timelapse interactively in the browser, not quite ready to show, but I am having great fun 😉

**Comment by wmww** [comment]
@Rialgar if/when the code is up please share. I might be interested in helping.

**Comment by Drakor** [comment]
@Rialgar I must admit, I'm currently just counting commits with a valid map, which means I'm overcounting, however, I think best definition would be: Turn 0 is the commit with the first valid map file and every other turn has "next turn" in the commit message ... the reason why I didn't do that so far is because I think that actually undercounts turns, but I'm not sure. I'm looking forward to see the interactive version!

**Comment by Drakor** [comment]
Here is the first video after tile decay was introduced: https://www.youtube.com/watch?v=-AlFWTtar4I

**Comment by Rialgar** [comment]
update: I now have it working to my liking for just the map (no @ symbols, player names, or stats, yet). I will do some cleanup, set up a branch for github pages and add documentation tomorrow and then push it and link it here.

I had to do pre-processing offline because retrieving it directly from git is just too slow. So I run my pre-process script and then the result can be used in an interactive web-page.

**Comment by Rialgar** [comment]
page showing timelapse: https://rialgar.github.io/gitland_timelapse/index.html

and of course the repo is at https://github.com/Rialgar/gitland_timelapse

At the moment I update the pre-processed bits manually once in a while, I want to set up something automated but did not get to it, yet.

**Comment by SimonMiaou** [comment]
@Rialgar Awesome! That's a great start

**Comment by Drakor** [comment]
@Rialgar That looks really good already, nice work!

(Here is a current timelapse up to turn 8851: https://www.youtube.com/watch?v=bbmSxWw5TQs )
