### ISSUE TITLE
raw.githubusercontent.com does not update in real time

### ISSUE THREAD

**Issue by wmww** [programical/gitland#45]
My bot was continuing to go in an old direction for several minutes before changing. I tracked to issue down to the raw github content being updated slower than the human-readable version. Try it by pushing a change to a file. The "normal" GH view will update next time you refresh, but the raw version wont. This is apparently because of cache control: https://stackoverflow.com/questions/46551413/github-not-update-raw-after-commit. Not sure what there is to be done about it. As a last resort, we could request the full HTML site and pull out the action somehow.

**Comment by programical** [comment]
This is a big problem for any bot that tries to do precise movements. Perhaps we could make API requests for the content? I'm not sure if that's supported.
