### ISSUE TITLE
For balancing it might be a good idea to automatically assign teams

### ISSUE THREAD

**Issue by jas32096** [programical/gitland#52]
Because people can pick their own teams, team sizes could quickly become unbalanced.

I propose changing joining, such that rather than putting your desired team as the title, just having the title be _join_ and having a team be assigned by the server, based on whichever team has the fewest members.

**Comment by Richienb** [comment]
Red team has 7 players, blue team has 18.

**Comment by Richienb** [comment]
@programical The best way to do this is to automatically assign a label to an issue which is read instead of the title.
