### ISSUE TITLE
Changes to the server and it's standards

### ISSUE THREAD

**Issue by MrFastwind** [programical/gitland#57]
Could be a  good idea cleaning the code of the server, and standardize it's map/users information? 
as how it's actually, it has duplicated info from map and players positions.
and (like you write is made on the run) is a little wonky, some thing could be finalized (move from a list of list of strings to a key,value where the key is (x, y) and the value is the type of terrain)

**Comment by MrFastwind** [comment]
as now my client takes from your code, all the writing and data gathering but it use Enums, and Classes to clean it out

**Comment by programical** [comment]
That would probably require a complete rewrite. Not sure if it's worth it.

**Comment by SimonMiaou** [comment]
How would you want to standardise the data? We could cleanup player list maybe, merge files but we should keep a simple format.

**Comment by MrFastwind** [comment]
> would you want to standardise the data? We could cleanup player list maybe, merge files but we should keep a simple format.

actually the only thing that we could change is only in the virtual side, because if we change the saved structure it would be necessary for all the players to change the clients code.

**Comment by MrFastwind** [comment]
than it will remain only refactoring the code of the server
