### ISSUE TITLE
Larger map

### ISSUE THREAD

**Issue by Richienb** [programical/gitland#65]
With this many people playing, the original 20x20 map might be too small to even hold the players. Maybe expand it to 30x30 or automatically increase its size based on the number of players.

**Comment by programical** [comment]
That would require changing the size of the icons to avoid automatic wrapping. Dynamic size would probably break many of the bots. I think it would be better to start with #66 to deal with the overpopulation.

**Comment by programical** [comment]
The map size will not be changed. Overpopulation is already being addressed by other means, and we don't want to confuse the bots more than we need to.
