### ISSUE TITLE
Kick inactive players

### ISSUE THREAD

**Issue by SimonMiaou** [programical/gitland#66]
As some players join the game to try-out and never come back again, we could think about kicking players that are inactive for a while (24h to start?) to let space for new players.

**Comment by Richienb** [comment]
The timeout shout be at least 4 days in case servers or code goes temporarily down for maintenance.

**Comment by programical** [comment]
This could be achieved by adding a timestamp file for every player. And I think 3 days sounds reasonable.

**Comment by programical** [comment]
How about removing players with no valid command inside their act file? This would of course be added to the README.

**Comment by SimonMiaou** [comment]
> How about removing players with no valid command inside their act file? 

Then we should have a command to not move.
My bot create an empty `act` file when no movement is possible.

Also this doesn't clean players that don't update the `act` file anymore.

**Comment by programical** [comment]
> Then we should have a command to not move.
> My bot create an empty `act` file when no movement is possible.
> 
> Also this doesn't clean players that don't update the `act` file anymore.

Added the "idle" command. We can deal with the rest of inactive players later. This will get rid of at least some of them. I plan to start enforcing the new rules tomorrow.

**Comment by SimonMiaou** [comment]
Perfect!
Don't have much python experience but I can look into adding timestamp file for each player when I find a bit of time

**Comment by wmww** [comment]
> How about removing players with no valid command inside their act file? This would of course be added to the README.

I don't think players should get kicked for an invalid file. It would be a pain to have to rejoin every time they make a mistake or their bot has a bug.

**Comment by SimonMiaou** [comment]
@programical With the current implementation, only players that didn't have any valid commands will be kicked after 24h.
But we still keep players that are stuck on the border as they don't update their `act` file anymore.

I think the kick should happen for any players that didn't move for more than 24h.
I created a suggestion in #86
