### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by programical** [programical/gitland#68]
Every time there's a change, I have to manually stop the server, "git pull", and start the server again. This could be solved by adding a pull command right after the sleep(), before any local changes are made.

**Comment by MrFastwind** [comment]
> Every time there's a change, I have to manually stop the server, "git pull", and start the server again. This could be solved by adding a pull command right after the sleep(), before any local changes are made.

well no, because the python code is already running, it doesn't reload in ram the code it self

**Comment by SimonMiaou** [comment]
Or we need to run the python script in a loop instead of having the loop in the python script? 🤔

**Comment by MrFastwind** [comment]
> Or we need to run the python script in a loop instead of having the loop in the python script? 🤔

well:
1) that require another script
2 )if it's written in python i think it will re import the new code

**Comment by programical** [comment]
> well no, because the python code is already running, it doesn't reload in ram the code it self
I was thinking about changes to files other than the server itself.

**Comment by MrFastwind** [comment]
i was working on a Dockerfile for my bot, but the problem is git, its need ssh key, and configurations to work with, and the fact that it's need to be rebuilded every time

**Comment by MrFastwind** [comment]
> > well no, because the python code is already running, it doesn't reload in ram the code it self
> 
> I was thinking about changes to files other than the server itself.

out of the server it self it's not a problem, however it's better if you work on another branch and make the merging from your side before pushing, and than make the server pull in the life cicle before pushing

**Comment by Richienb** [comment]
Just poll for new updates then pull and restart the script.
