### ISSUE TITLE
Tile decay

### ISSUE THREAD

**Issue by programical** [programical/gitland#71]
Here's an idea for a new mechanic.

If a tile isn't touched by any player for 10 turns, it turns back into a gray tile (ux).

This could be implemented by adding a second map file that holds one digit (0-9) per tile. Every turn, if there is a player on a tile, its number is set back to 0. Otherwise, it increases by 1. Once it reaches 9, the tile is set to `ux`.

Thoughts? I imagine this would make holding a lot of territory more difficult.

**Comment by SimonMiaou** [comment]
Notes following discussion on discord:
10 turns is a bit quick and the decay should be slower.

> well, there is 18 active players, means 180 tiles max covered in 10 turns ... with 529 tiles, that leaves 349 that presumably can't be touched in 10 turns - YaoAngelsin

30 turns could be a nice start

**Comment by programical** [comment]
Testing this in `decay-testing` branch right now.

**Comment by programical** [comment]
Tile decay implemented.
