### ISSUE TITLE
Win condition

### ISSUE THREAD

**Issue by programical** [programical/gitland#72]
There should be a way to win.

**Comment by tkshnwesper** [comment]
I suppose a win condition for red could be:

if you are red,
number of blue squares equals the number of blue players,
number of green squares equals the number of green players

**Comment by programical** [comment]
- Control of the entire map is not possible, because some tiles have players on them. 
- Control of x% of the map is unreliable, because the more players there are, the less territory can be controlled by a single team.
- Control of all non-player tiles is not realistically achievable.
- Control of x% of non-player tiles could work (assuming x > 50)

**Comment by SimonMiaou** [comment]
> Control of x% of non-player tiles could work (assuming x > 50)

We could also add that the control need to be kept for X turns

**Comment by tkshnwesper** [comment]
>     * Control of the entire map is not possible, because some tiles have players on them.

It's possible to "box in" enemy players so they cannot move, but that would also mean that the players who box in other players also cannot move 😄 

>     * Control of x% of the map is unreliable, because the more players there are, the less territory can be controlled by a single team.

True, if the win condition is going to be a percentage, then it has to be a function of the number of players.

>     * Control of all non-player tiles is not realistically achievable.

I think once all enemy players are boxed in, and no new players are added for a short window of time until the winning team captures all the non-player tiles, it could be achieved, and once that happens no new enemy players can be added to the grid.

**Comment by robsheldon** [comment]
You can probably just look for an asymptotic game state -- where one team is dominating the board, and the team percentages have stopped substantially changing.

If one team controls 67+% of non-player tiles for an hour, and both of the other two teams have less than 20% of non-player tiles over the same hour, then the game has probably ended. The game state wouldn't be likely to change very much without new players.

**Comment by acasajus** [comment]
Why should there be a condition to win?

**Comment by jas32096** [comment]
@tkshnwesper I also thought about boxing in players, as a strategy, but it's easily defended by leaving and rejoining.

**Comment by tkshnwesper** [comment]
> @tkshnwesper I also thought about boxing in players, as a strategy, but it's easily defended by leaving and rejoining.

Yeah, that's a good point @jas32096.

**Comment by SimonMiaou** [comment]
> Why should there be a condition to win?

I like the idea of resetting the game at some point, when nothing interesting happen as clearly a team dominate the board.

**Comment by SimonMiaou** [comment]
As right now the team with most control keep changing over time, we could have a winning condition based on the length a team can keep the first place.
For example, if a lead have the lead for a strike more than 720 turns (12 hours) we could say it wins.
Then we reset the board and maybe shuffle the teams.

That would also allow us to have a top player list, each team victory give a point to each player of the team. We could then assume that player with most victory are either really lucky or develop a BOT that help significantly the teams he joined.

What do you think about this idea? So far I don't think a team managed to keep the lead for more than 12h but I didn't check that.

**Comment by suvakov** [comment]
I like top players list in time-lapse videos. Can we have something similar here? E.g., three files updated after each move:
top_players_daily
top_players_weekly
top_players_all_time
with list of players and number of fields they colored. What do you think?
