### ISSUE TITLE
Increase decay time?

### ISSUE THREAD

**Issue by wmww** [programical/gitland#79]
In my humble opinion, the decay time is too short. Since a player can claim a square for at most 30 turns, the benefit of strategically claiming squares less likely to be reclaimed is lessened. I like the idea of decay, but I vote for bumping the limit up significantly (60? 100?). What do y'all think?

**Comment by robsheldon** [comment]
I'm not sure what problem tile decay is trying to solve but so far I don't think it has improved the game.

With tile decay as it is now, somebody could write a simple bot that goes down the map, right one square, up the map, left one square, down the map... and, along with some rudimentary obstacle avoidance, it would be one of the better bots on the board. Tile decay has made this game easier to play well, not harder.

**Comment by Drakor** [comment]
I agree with this, and I think it should at least be double what it is now.
Currently the team with the most active players has an easier time leaving the biggest trail. At the time of writing the red team has a larger claimed area than smaller teams could feasibly claim, even if they played flawlessly.
That being said, what I like about the decay system is that it increases the importance of claiming enemy tiles as well as making the success of a team much more dependent on their current strategy and what their active bots are doing.

**Comment by SimonMiaou** [comment]
Fully agree with all that was said.

I like the idea of having square that does back to black when not visited for a long time, like maybe half a day or at least a few hours.
360 turn for a square to decay would means the square was not visited for more than 6h. Right now it is less than 1h.

> I'm not sure what problem tile decay is trying to solve

The decay feature was an idea of new mechanic, to bring more to the game. During the short discussion on discord we were wondering how it would affect the balance. We had to try to know :)

**Comment by programical** [comment]
Decay now takes 90 turns.
